In [122]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [123]:
titanic_df = pd.read_csv('./data/train.csv')
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [124]:
y_titanic_df = titanic_df['Survived']
X_titanic_df = titanic_df.drop('Survived', axis=1)
X_titanic_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [125]:
X_titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Pclass       891 non-null    int64
 2   Name         891 non-null    str
 3   Sex          891 non-null    str
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    str
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    str
 10  Embarked     889 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 76.7 KB

In [126]:
test_df = pd.read_csv('./data/test.csv')

res = test_df['PassengerId']
test_df.tail()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [127]:
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 36.1 KB

In [128]:
for df in [X_titanic_df, test_df]:
    df['Age'] = df['Age'].fillna(df['Age'].mean())
    df['Cabin'] = df['Cabin'].fillna('N')
    df['Embarked'] = df['Embarked'].fillna('N')
    df['Fare'] = df['Fare'].fillna(0)
    df['Cabin'] = df['Cabin'].str[:1]

for df in [X_titanic_df, test_df]:
    print(df.isnull().sum())

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64
PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [129]:
drop_col = ['PassengerId', 'Name', 'Ticket']
X_titanic_df = X_titanic_df.drop(columns = drop_col)
test_df = test_df.drop(columns = drop_col)

In [130]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder

In [131]:
oe = OrdinalEncoder(handle_unknown = 'use_encoded_value', unknown_value=-1)
X_titanic_df[['Cabin', 'Sex', 'Embarked']] = oe.fit_transform(X_titanic_df[['Cabin', 'Sex', 'Embarked']])
test_df[['Cabin', 'Sex', 'Embarked']] = oe.transform(test_df[['Cabin', 'Sex', 'Embarked']])

In [132]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_titanic_df, y_titanic_df, test_size=0.2, random_state=42
)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_train, y_train, test_size=0.25, random_state=42
)

In [133]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 모델 생성

dt_clf = DecisionTreeClassifier(random_state=42)
rf_clf = RandomForestClassifier(random_state=42)
lr_clf = LogisticRegression(solver='liblinear')

# 모델 학습 및 검증

dt_clf.fit(X_train, y_train)
dt_pred = dt_clf.predict(X_valid)
print('DecisionTree Accuracy:', accuracy_score(y_valid, dt_pred))

rf_clf.fit(X_train, y_train)
rf_pred = rf_clf.predict(X_valid)
print('RandomForest Accuracy:', accuracy_score(y_valid, rf_pred))

lr_clf.fit(X_train, y_train)
lr_pred = lr_clf.predict(X_valid)
print('LogisticRegression Accuracy:', accuracy_score(y_valid, lr_pred))

DecisionTree Accuracy: 0.7808988764044944
RandomForest Accuracy: 0.8089887640449438
LogisticRegression Accuracy: 0.8033707865168539

In [134]:
dt_test = dt_clf.predict(test_df)
rf_test = rf_clf.predict(test_df)
lr_test = lr_clf.predict(test_df)

result = pd.DataFrame({'PassengerId': res,
                       'DecisionTree': dt_test,
                       'RandomForest': rf_test,
                       ':LogisticRegression': lr_test})

result.head()

   PassengerId  DecisionTree  RandomForest  :LogisticRegression
0          892             1             0                    0
1          893             0             0                    0
2          894             1             0                    0
3          895             1             0                    0
4          896             1             1                    1

In [135]:
result['DecisionTree'].value_counts()

DecisionTree
0    246
1    172
Name: count, dtype: int64