In [1]:
import pandas as pd
import seaborn as sns

In [2]:
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex', 'class', 'fare', 'survived']]
df.head()

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

In [3]:
pdf1 = pd.pivot_table(df,             
                     index='class',    
                     columns='sex',   
                     values='age',    
                     aggfunc='mean',  
                     observed=True)
pdf1

sex        female       male
class
First   34.611765  41.281386
Second  28.722973  30.740707
Third   21.750000  26.507589

In [4]:
pdf2 = pd.pivot_table(df,                       
                     columns='sex',            
                     values='survived',         
                     aggfunc=['mean', 'sum'],  
                     observed=True)
pdf2

              mean              sum
sex         female      male female male
survived  0.742038  0.188908    233  109

In [5]:
pdf3 = pd.pivot_table(df,                       
                     index=['class', 'sex'],    
                     columns='survived',       
                     values=['age', 'fare'],    
                     aggfunc=['mean', 'max'],  
                     observed=True)
pdf3

                    mean                                      max        \
                     age                   fare               age
survived               0          1           0           1     0     1
class  sex
First  female  25.666667  34.939024  110.604167  105.978159  50.0  63.0
       male    44.581967  36.248000   62.894910   74.637320  71.0  80.0
Second female  36.000000  28.080882   18.250000   22.288989  57.0  55.0
       male    33.369048  16.022000   19.488965   21.095100  70.0  62.0
Third  female  23.818182  19.329787   19.773093   12.464526  48.0  63.0
       male    27.255814  22.274211   12.204469   15.579696  74.0  45.0


                 fare
survived            0         1
class  sex
First  female  151.55  512.3292
       male    263.00  512.3292
Second female   26.00   65.0000
       male     73.50   39.0000
Third  female   69.55   31.3875
       male     69.55   56.4958