In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./data/auto-mpg.csv',header=None)

df.columns = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model year', 'origin','name']

df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite

In [3]:
mpg_to_kpl = 1.60934/3.78541

df['kpl'] = df['mpg'] * mpg_to_kpl

df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.652571
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.377143
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.652571

In [4]:
df['kpl'] = df['kpl'].round(2)
df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.65

In [5]:
print(df['horsepower'].unique())

<StringArray>
['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0', '225.0',
 '190.0', '170.0', '160.0', '95.00', '97.00', '85.00', '88.00', '46.00',
 '87.00', '90.00', '113.0', '200.0', '210.0', '193.0',     '?', '100.0',
 '105.0', '175.0', '153.0', '180.0', '110.0', '72.00', '86.00', '70.00',
 '76.00', '65.00', '69.00', '60.00', '80.00', '54.00', '208.0', '155.0',
 '112.0', '92.00', '145.0', '137.0', '158.0', '167.0', '94.00', '107.0',
 '230.0', '49.00', '75.00', '91.00', '122.0', '67.00', '83.00', '78.00',
 '52.00', '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
 '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0', '108.0',
 '68.00', '58.00', '149.0', '89.00', '63.00', '48.00', '66.00', '139.0',
 '103.0', '125.0', '133.0', '138.0', '135.0', '142.0', '77.00', '62.00',
 '132.0', '84.00', '64.00', '74.00', '116.0', '82.00']
Length: 94, dtype: str

In [6]:
import numpy as np

df['horsepower'] = df['horsepower'].replace('?',np.nan)
df = df.dropna(subset=['horsepower'],axis=0)
df['horsepower'] = df['horsepower'].astype('float')

print(df['horsepower'].dtypes)

float64

In [7]:
print(df['origin'].unique())

df['origin'] = df['origin'].replace({1:'USA', 2:'EU', 3:'JAPAN'})

print(df['origin'].unique())
print(df['origin'].dtypes)

[1 3 2]
['USA' 'JAPAN' 'EU']
object

In [9]:
df[300:306]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
302,34.5,4,105.0,70.0,2150.0,14.9,79,USA,plymouth horizon tc3,14.67
303,31.8,4,85.0,65.0,2020.0,19.2,79,JAPAN,datsun 210,13.52
304,37.3,4,91.0,69.0,2130.0,14.7,79,EU,fiat strada custom,15.86
305,28.4,4,151.0,90.0,2670.0,16.0,79,USA,buick skylark limited,12.07
306,28.8,6,173.0,115.0,2595.0,11.3,79,USA,chevrolet citation,12.24
307,26.8,6,173.0,115.0,2700.0,12.9,79,USA,oldsmobile omega brougham,11.39

In [11]:
df['origin'] = df['origin'].astype('category')
print(df['origin'].dtypes)

df['origin'] = df['origin'].astype('object')
print(df['origin'].dtypes)

category
object

In [12]:
print(df['model year'].sample(3))
df['model year'] = df['model year'].astype('category')
print(df['model year'].sample(3))

246    78
5      70
263    78
Name: model year, dtype: int64
221    77
89     73
205    76
Name: model year, dtype: category
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]